-- Project Memory SQLite Schema
-- Generated by: project-memory-bootstrap

CREATE TABLE IF NOT EXISTS modules (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    path TEXT,
    purpose TEXT,
    memory_file TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS services (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    module_id TEXT REFERENCES modules(id),
    path TEXT,
    methods TEXT,
    callers TEXT,
    memory_file TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS repositories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    module_id TEXT REFERENCES modules(id),
    storage_backend TEXT,
    tables_or_collections TEXT,
    memory_file TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS apis (
    id TEXT PRIMARY KEY,
    group_name TEXT NOT NULL,
    protocol TEXT,
    base_path TEXT,
    memory_file TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS entities (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT,
    module_id TEXT REFERENCES modules(id),
    memory_file TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS lessons (
    id TEXT PRIMARY KEY,
    category TEXT,
    title TEXT,
    context TEXT,
    problem TEXT,
    resolution TEXT,
    impact TEXT,
    recommendation TEXT,
    recorded_at TEXT
);

CREATE TABLE IF NOT EXISTS memory_meta (
    key TEXT PRIMARY KEY,
    value TEXT
);
